name: live_cells_core
description: > 
  Provides the core of live cells: A replacement for ChangeNotifier and ValueNotifier
  that is easier to use and more flexible
version: 0.11.0
repository: https://github.com/alex-gutev/live_cells/tree/master/live_cells_core
issue_tracker: https://github.com/alex-gutev/live_cells/issues

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  live_cell_annotations: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8