name: live_cells
description: A replacement for ChangeNotifier and ValueNotifier that is easier to use and more flexible
version: 0.23.6
repository: https://github.com/alex-gutev/live_cells/tree/master/live_cells
issue_tracker: https://github.com/alex-gutev/live_cells/issues
homepage: https://livecell.gutev.dev/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  live_cell_annotations: ^0.4.3
  live_cells_core: ^0.23.5
  live_cell_widgets: ^0.10.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=2.0.0'

topics:
  - reactive
  - state-management
  - state-restoration
  - extension
  - ui